# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba86ecf55adc07b1a5eb321207a88d017fd1d3b8d90b0602bf096a19b019d4c6d041d60e7d05e5ce629f704b1f8233b4e33ca3d9fb4bb9cf0a99617efb995682

test:
  secret_key_base: 084ce685163b46f0ac505cadff135f4943bad2892fbbe509dfb63bf0f56e649381e2a1942c8f33ab9225c68f0249a1fbcfa14538211d2039a4cbecbaa7aab68f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
